package 
{
	public class TryCatchTest
	{
		public static function Main():int
		{
			var c:int;
	
			try {
				throw new Error ();
				return 1;
			} catch (e) {
				trace (typeof (e));
				trace (e);
				c++;
			}

			if (c != 1)
				return 2;
			
			try {
				throw new ArgumentError ();
			} catch (e:ArgumentError) {
				++c;
			} catch (e:ArgumentError) {
				return 3;
			}
			
			if (c != 2)
				return 4;
				
			try {
				throw new Error ();
			} catch (e:*) {
				++c;
			}
			
			if (c != 3)
				return 5;

// TODO:
/*
			try {
				throw new String ("aa");
			} catch (e:String) {
				++c;
			} catch (e:Number) {
				return 5;
			}

			if (c != 2)
				return 6;

			try {
				throw null; // TODO: Need to wrap it
			} catch (e:*) {
				++c;
			}
			
			if (c != 3)
				return 5;
*/

			return 0;
		}
	}
}
